spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/courses-manager-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: email-smtp.sa-east-1.amazonaws.com
    port: 587
    username: AKIAWTKIPISH7MJH72HB
    password: BO33MQd4PLgBaDPfgq6XfadqTUEKNP7A7CL7BB6WeiSH
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 3333

# KEYCLOAK CONFIGURATION
keycloak:
  realm: courses-manager
  resource: courses-manager-api
  auth-server-url: http://localhost:8080
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username

# SWAGGER CONFIGURATION
springdoc:
  swagger-ui:
#    path: swagger-ui.html
    operations-sorter: method