spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/courses-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/courses-manager-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 3333

# KEYCLOAK CONFIGURATION
keycloak:
  realm: courses-manager
  resource: courses-manager-api
  auth-server-url: http://localhost:8080
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username



# SWAGGER CONFIGURATION
springdoc:
  swagger-ui:
#    path: swagger-ui.html
    operations-sorter: method